"""Persistent NTP/SNTP configuration for the read-only PDU image."""

import ipaddress
import json
import logging
import os
import re
import tempfile
from typing import Any, Dict

from ttne import utils


logger = logging.getLogger(__name__)

NTP_SETTINGS_FILE = "/home/root/.ne/ntp_settings.json"
CHRONY_CONFIG_FILE = "/home/root/.ne/chrony.conf"
NTP_DISABLED_FILE = "/home/root/.ne/ntp_disabled"
CHRONY_INIT = "/etc/init.d/chronyd"
DEFAULT_NTP_SERVER = "0.openembedded.pool.ntp.org"
DEFAULT_SETTINGS = {
    "enabled": True,
    "time_offset": 0,
    "server": DEFAULT_NTP_SERVER,
}

_HOST_LABEL = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")


def validate_server(value: str) -> str:
    """Return a safe IP address or DNS hostname for a Chrony directive."""
    server = str(value or "").strip()
    # Keep this aligned with APP_STATE_NW_TEXT_LEN in ttne-display so values
    # entered through the API can always be represented without truncation.
    if not server or len(server) > 127 or any(char.isspace() for char in server):
        raise ValueError("NTP server must be a valid IP address or DNS hostname")
    try:
        ipaddress.ip_address(server)
        return server
    except ValueError:
        pass

    hostname = server[:-1] if server.endswith(".") else server
    if not hostname or any(not _HOST_LABEL.fullmatch(label)
                           for label in hostname.split(".")):
        raise ValueError("NTP server must be a valid IP address or DNS hostname")
    return server


def normalize_settings(settings: Dict[str, Any]) -> Dict[str, Any]:
    enabled = settings.get("enabled", DEFAULT_SETTINGS["enabled"])
    if not isinstance(enabled, bool):
        raise ValueError("NTP enabled must be a boolean")
    offset = settings.get("time_offset", DEFAULT_SETTINGS["time_offset"])
    if isinstance(offset, bool) or not isinstance(offset, int) or not -12 <= offset <= 12:
        raise ValueError("Time offset must be between UTC-12 and UTC+12")
    return {
        "enabled": enabled,
        "time_offset": offset,
        "server": validate_server(settings.get("server", DEFAULT_NTP_SERVER)),
    }


def _atomic_write(path: str, content: str, mode: int = 0o644) -> None:
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".ntp-", dir=directory,
                                              text=True)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def render_chrony_config(settings: Dict[str, Any]) -> str:
    normalized = normalize_settings(settings)
    return (
        "# Generated by ne-fw-api. Do not edit manually.\n"
        f"server {normalized['server']} iburst\n"
        "makestep 1.0 -1\n"
        "driftfile /var/lib/chrony/drift\n"
        "rtcsync\n"
        "logdir /var/log/chrony\n"
    )


def load_settings() -> Dict[str, Any]:
    try:
        with open(NTP_SETTINGS_FILE, "r", encoding="utf-8") as settings_file:
            return normalize_settings(json.load(settings_file))
    except FileNotFoundError:
        return dict(DEFAULT_SETTINGS)
    except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
        logger.warning("Invalid NTP settings; using defaults: %s", exc)
        return dict(DEFAULT_SETTINGS)


def save_settings(settings: Dict[str, Any]) -> Dict[str, Any]:
    normalized = normalize_settings(settings)
    _atomic_write(CHRONY_CONFIG_FILE, render_chrony_config(normalized))
    _atomic_write(
        NTP_SETTINGS_FILE,
        json.dumps(normalized, indent=2, sort_keys=True) + "\n",
        mode=0o600,
    )
    if normalized["enabled"]:
        try:
            os.unlink(NTP_DISABLED_FILE)
        except FileNotFoundError:
            pass
    else:
        _atomic_write(NTP_DISABLED_FILE, "disabled\n", mode=0o600)
    return normalized


async def apply_settings(settings: Dict[str, Any]) -> bool:
    normalized = save_settings(settings)
    action = "restart" if normalized["enabled"] else "stop"
    return_code, output = await utils.exec_command(CHRONY_INIT, action)
    if return_code != 0:
        logger.error("Could not %s Chrony: %s", action, output.strip())
        return False
    return True


async def restore_settings() -> bool:
    settings = load_settings()
    # Write defaults on first boot and regenerate a missing Chrony file.
    if (not os.path.isfile(NTP_SETTINGS_FILE)
            or not os.path.isfile(CHRONY_CONFIG_FILE)):
        save_settings(settings)
    action = "restart" if settings["enabled"] else "stop"
    return_code, output = await utils.exec_command(CHRONY_INIT, action)
    if return_code != 0:
        logger.error("Could not restore NTP service: %s", output.strip())
        return False
    return True


async def service_status() -> Dict[str, bool]:
    settings = load_settings()
    if not settings["enabled"]:
        return {"running": False, "synchronized": False}
    # Avoid reverse-DNS lookups here. On isolated PDU networks chronyc can
    # print tracking data and then wait indefinitely while resolving the
    # selected source, which would leave the API request open.
    return_code, output = await utils.exec_command("chronyc", "-n", "tracking")
    if return_code != 0:
        return {"running": False, "synchronized": False}
    synchronized = any(
        key.strip().lower() == "leap status"
        and value.strip().lower() == "normal"
        for line in output.splitlines()
        for key, separator, value in (line.partition(":"),)
        if separator
    )
    return {"running": True, "synchronized": synchronized}
