#! /usr/bin/env bash
FILE="$HOME/.ne/logs/log"

printf "\n\033[1m\033[36mTycheTools Network Engineering log (press CTRL-C to exit)\033[0m\n\n"

if [[ ! -e $FILE ]]; then
	mkdir -p $(dirname -- $FILE)
	touch $FILE
fi
tail -F $FILE 2> /dev/null
